import os

def w(path, content):
    os.makedirs(os.path.dirname(path) if os.path.dirname(path) else ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Written: {path}")

# ── app/core/config.py ────────────────────────────────────────────────────────
w("app/core/config.py", "\n".join([
    "from pydantic_settings import BaseSettings",
    "from pydantic import Field",
    "from functools import lru_cache",
    "",
    "",
    "class Settings(BaseSettings):",
    '    app_name: str = "PaperForge"',
    '    app_version: str = "0.1.0"',
    '    environment: str = Field(default="development", alias="ENVIRONMENT")',
    '    log_level: str = Field(default="INFO", alias="LOG_LEVEL")',
    "    cors_origins: list[str] = Field(",
    '        default=["http://localhost:3000"], alias="CORS_ORIGINS"',
    "    )",
    '    anthropic_api_key: str = Field(..., alias="ANTHROPIC_API_KEY")',
    '    claude_model: str = Field(default="claude-sonnet-4-20250514", alias="CLAUDE_MODEL")',
    '    claude_max_tokens: int = Field(default=4096, alias="CLAUDE_MAX_TOKENS")',
    '    supabase_url: str = Field(..., alias="SUPABASE_URL")',
    '    supabase_service_key: str = Field(..., alias="SUPABASE_SERVICE_KEY")',
    '    max_pdf_size_mb: int = Field(default=20, alias="MAX_PDF_SIZE_MB")',
    '    arxiv_request_timeout: int = Field(default=30, alias="ARXIV_REQUEST_TIMEOUT")',
    "",
    '    model_config = {"env_file": ".env", "populate_by_name": True}',
    "",
    "    @property",
    "    def max_pdf_size_bytes(self) -> int:",
    "        return self.max_pdf_size_mb * 1024 * 1024",
    "",
    "    @property",
    "    def is_production(self) -> bool:",
    '        return self.environment == "production"',
    "",
    "",
    "@lru_cache()",
    "def get_settings() -> Settings:",
    "    return Settings()",
]))

# ── app/core/logging.py ───────────────────────────────────────────────────────
w("app/core/logging.py", "\n".join([
    "import logging",
    "import sys",
    "from app.core.config import get_settings",
    "",
    "",
    "def setup_logging() -> None:",
    "    settings = get_settings()",
    "    level = getattr(logging, settings.log_level.upper(), logging.INFO)",
    "    handler = logging.StreamHandler(sys.stdout)",
    "    handler.setLevel(level)",
    "    formatter = logging.Formatter(",
    '        fmt="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",',
    '        datefmt="%Y-%m-%d %H:%M:%S",',
    "    )",
    "    handler.setFormatter(formatter)",
    "    root_logger = logging.getLogger()",
    "    root_logger.setLevel(level)",
    "    root_logger.handlers.clear()",
    "    root_logger.addHandler(handler)",
    '    logging.getLogger("httpx").setLevel(logging.WARNING)',
    '    logging.getLogger("httpcore").setLevel(logging.WARNING)',
    "",
    "",
    "def get_logger(name: str) -> logging.Logger:",
    "    return logging.getLogger(name)",
]))

# ── app/core/exceptions.py ────────────────────────────────────────────────────
w("app/core/exceptions.py", "\n".join([
    "from fastapi import HTTPException, status",
    "",
    "",
    "class PaperForgeError(Exception):",
    "    pass",
    "",
    "class PaperFetchError(PaperForgeError):",
    "    pass",
    "",
    "class PaperParseError(PaperForgeError):",
    "    pass",
    "",
    "class PaperTooLargeError(PaperForgeError):",
    "    pass",
    "",
    "class InvalidArxivIdError(PaperForgeError):",
    "    pass",
    "",
    "class AnalysisError(PaperForgeError):",
    "    pass",
    "",
    "class ClaudeAPIError(PaperForgeError):",
    "    pass",
    "",
    "",
    "def http_not_found(detail: str) -> HTTPException:",
    "    return HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=detail)",
    "",
    "def http_bad_request(detail: str) -> HTTPException:",
    "    return HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=detail)",
    "",
    "def http_unprocessable(detail: str) -> HTTPException:",
    "    return HTTPException(status_code=status.HTTP_422_UNPROCESSABLE_ENTITY, detail=detail)",
    "",
    "def http_service_unavailable(detail: str) -> HTTPException:",
    "    return HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=detail)",
    "",
    "def http_payload_too_large(detail: str) -> HTTPException:",
    "    return HTTPException(status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE, detail=detail)",
]))

# ── app/models/paper.py ───────────────────────────────────────────────────────
w("app/models/paper.py", "\n".join([
    "from pydantic import BaseModel, Field, field_validator",
    "from typing import Optional",
    "from enum import Enum",
    "import re",
    "",
    "",
    "class ImplementationDifficulty(str, Enum):",
    '    EASY = "easy"',
    '    MEDIUM = "medium"',
    '    HARD = "hard"',
    "",
    "",
    "class PaperSource(str, Enum):",
    '    ARXIV_URL = "arxiv_url"',
    '    PDF_UPLOAD = "pdf_upload"',
    "",
    "",
    "class ParseArxivRequest(BaseModel):",
    '    url: str = Field(..., description="ArXiv paper URL or ID")',
    "",
    "    @field_validator('url')",
    "    @classmethod",
    "    def validate_arxiv_url(cls, v: str) -> str:",
    "        v = v.strip()",
    "        patterns = [",
    r'            r"arxiv\.org/(abs|pdf)/(\d{4}\.\d{4,5}(v\d+)?)",',
    r'            r"^(\d{4}\.\d{4,5}(v\d+)?)$",',
    r'            r"arxiv\.org/(abs|pdf)/([a-z\-]+/\d{7}(v\d+)?)",',
    "        ]",
    "        for p in patterns:",
    "            if re.search(p, v, re.IGNORECASE):",
    "                return v",
    "        raise ValueError(",
    '            "Must be a valid arXiv URL (e.g. https://arxiv.org/abs/2301.07041) "',
    '            "or bare arXiv ID (e.g. 2301.07041)"',
    "        )",
    "",
    "",
    "class ParsedPaper(BaseModel):",
    "    arxiv_id: Optional[str] = None",
    "    title: str",
    "    authors: list[str] = Field(default_factory=list)",
    "    abstract: str",
    "    full_text: str",
    "    page_count: int",
    "    word_count: int",
    "    source: PaperSource",
    "    pdf_url: Optional[str] = None",
    "",
    "",
    "class PaperAnalysis(BaseModel):",
    "    title: str",
    "    problem_statement: str",
    "    proposed_method: str",
    "    key_algorithm: str",
    "    novelty: str",
    "    datasets_used: list[str] = Field(default_factory=list)",
    "    evaluation_metrics: list[str] = Field(default_factory=list)",
    "    reported_results: dict[str, str] = Field(default_factory=dict)",
    "    implementation_difficulty: ImplementationDifficulty",
    "    dependencies: list[str] = Field(default_factory=list)",
    "    reproducibility_notes: str",
    "    paper_type: str",
    "    is_implementable: bool",
    "",
    "",
    "class ParseResponse(BaseModel):",
    "    success: bool = True",
    "    arxiv_id: Optional[str]",
    "    title: str",
    "    authors: list[str]",
    "    abstract: str",
    "    page_count: int",
    "    word_count: int",
    "    source: PaperSource",
    '    message: str = "Paper parsed successfully"',
    "",
    "",
    "class AnalyzeResponse(BaseModel):",
    "    success: bool = True",
    "    arxiv_id: Optional[str]",
    "    analysis: PaperAnalysis",
    "    tokens_used: int",
    '    message: str = "Analysis complete"',
    "",
    "",
    "class HealthResponse(BaseModel):",
    '    status: str = "ok"',
    "    version: str",
    "    environment: str",
]))

# ── app/utils/arxiv.py ────────────────────────────────────────────────────────
w("app/utils/arxiv.py", "\n".join([
    "import re",
    "from app.core.exceptions import InvalidArxivIdError",
    "",
    "_ARXIV_ID_PATTERNS = [",
    r'    re.compile(r"arxiv\.org/(?:abs|pdf)/(\d{4}\.\d{4,5}(?:v\d+)?)"),',
    r'    re.compile(r"arxiv\.org/(?:abs|pdf)/([a-z\-]+/\d{7}(?:v\d+)?)"),',
    r'    re.compile(r"^(\d{4}\.\d{4,5}(?:v\d+)?)$"),',
    r'    re.compile(r"^([a-z\-]+/\d{7}(?:v\d+)?)$"),',
    "]",
    "",
    "",
    "def extract_arxiv_id(url_or_id: str) -> str:",
    "    text = url_or_id.strip()",
    "    for pattern in _ARXIV_ID_PATTERNS:",
    "        match = pattern.search(text)",
    "        if match:",
    "            return match.group(1)",
    "    raise InvalidArxivIdError(",
    "        f'Could not extract arXiv ID from: {url_or_id!r}. '",
    "        'Expected format: https://arxiv.org/abs/2301.07041 or bare ID 2301.07041'",
    "    )",
    "",
    "",
    "def build_pdf_url(arxiv_id: str) -> str:",
    '    return f"https://arxiv.org/pdf/{arxiv_id}"',
    "",
    "",
    "def build_abs_url(arxiv_id: str) -> str:",
    '    return f"https://arxiv.org/abs/{arxiv_id}"',
    "",
    "",
    "def strip_version(arxiv_id: str) -> str:",
    r'    return re.sub(r"v\d+$", "", arxiv_id)',
]))

# ── app/utils/text.py ─────────────────────────────────────────────────────────
w("app/utils/text.py", "\n".join([
    "import re",
    "",
    "",
    "def clean_pdf_text(raw: str) -> str:",
    "    text = raw",
    r'    text = re.sub(r"-\n(\w)", r"\1", text)',
    r'    text = re.sub(r"\n{3,}", "\n\n", text)',
    '    text = text.replace("\\f", "\\n\\n")',
    r'    text = re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]", "", text)',
    '    text = text.replace("\\u2013", "-").replace("\\u2014", "--")',
    "    text = text.replace(\"\\u2018\", \"'\").replace(\"\\u2019\", \"'\")",
    '    text = text.replace("\\u201c", \'"\').replace("\\u201d", \'"\')',
    r'    text = re.sub(r"[ \t]{2,}", " ", text)',
    "    return text.strip()",
    "",
    "",
    "def extract_abstract(text: str) -> str:",
    "    patterns = [",
    r'        r"Abstract\s*\n+(.*?)(?:\n\n|\n1\s|Introduction)",',
    r'        r"ABSTRACT\s*\n+(.*?)(?:\n\n|\n1\s|INTRODUCTION)",',
    "    ]",
    "    for pattern in patterns:",
    "        match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)",
    "        if match:",
    "            abstract = match.group(1).strip()",
    r'            abstract = re.sub(r"\n+", " ", abstract)',
    "            return abstract[:2000]",
    "    return ''",
    "",
    "",
    "def truncate_for_claude(text: str, max_chars: int = 80000) -> str:",
    "    if len(text) <= max_chars:",
    "        return text",
    "    keep_start = int(max_chars * 0.85)",
    "    keep_end = max_chars - keep_start",
    "    start = text[:keep_start]",
    "    end = text[-keep_end:]",
    "    return start + '\\n\\n[... middle section truncated for length ...]\\n\\n' + end",
    "",
    "",
    "def count_words(text: str) -> int:",
    "    return len(text.split())",
]))

# ── app/api/routes/health.py ──────────────────────────────────────────────────
w("app/api/routes/health.py", "\n".join([
    "from fastapi import APIRouter",
    "from app.models.paper import HealthResponse",
    "from app.core.config import get_settings",
    "",
    'router = APIRouter(tags=["health"])',
    "settings = get_settings()",
    "",
    "",
    '@router.get("/health", response_model=HealthResponse, summary="Health check")',
    "async def health() -> HealthResponse:",
    "    return HealthResponse(",
    "        status='ok',",
    "        version=settings.app_version,",
    "        environment=settings.environment,",
    "    )",
]))

# ── app/api/routes/parse.py ───────────────────────────────────────────────────
w("app/api/routes/parse.py", "\n".join([
    "from fastapi import APIRouter, UploadFile, File",
    "from app.models.paper import ParseArxivRequest, ParseResponse, PaperSource",
    "from app.services.parser import fetch_arxiv_paper, parse_uploaded_pdf",
    "from app.core.exceptions import (",
    "    PaperFetchError, PaperParseError, PaperTooLargeError, InvalidArxivIdError,",
    "    http_bad_request, http_not_found, http_payload_too_large,",
    "    http_service_unavailable, http_unprocessable,",
    ")",
    "from app.core.logging import get_logger",
    "",
    'router = APIRouter(prefix="/parse", tags=["parse"])',
    "logger = get_logger(__name__)",
    "",
    "",
    '@router.post("/arxiv", response_model=ParseResponse)',
    "async def parse_arxiv(request: ParseArxivRequest) -> ParseResponse:",
    "    try:",
    "        paper = await fetch_arxiv_paper(request.url)",
    "    except InvalidArxivIdError as exc:",
    "        raise http_bad_request(str(exc))",
    "    except PaperFetchError as exc:",
    "        raise http_not_found(str(exc))",
    "    except PaperTooLargeError as exc:",
    "        raise http_payload_too_large(str(exc))",
    "    except PaperParseError as exc:",
    "        raise http_unprocessable(str(exc))",
    "    except Exception as exc:",
    '        logger.exception("Unexpected error: %s", exc)',
    '        raise http_service_unavailable("An unexpected error occurred.")',
    "    return ParseResponse(",
    "        arxiv_id=paper.arxiv_id, title=paper.title, authors=paper.authors,",
    "        abstract=paper.abstract, page_count=paper.page_count,",
    "        word_count=paper.word_count, source=PaperSource.ARXIV_URL,",
    "    )",
    "",
    "",
    '@router.post("/upload", response_model=ParseResponse)',
    "async def parse_upload(file: UploadFile = File(...)) -> ParseResponse:",
    "    content_type = file.content_type or ''",
    "    if 'pdf' not in content_type and not (file.filename or '').lower().endswith('.pdf'):",
    "        raise http_bad_request(f'Only PDF files accepted. Got: {content_type!r}')",
    "    try:",
    "        pdf_bytes = await file.read()",
    "    except Exception as exc:",
    "        raise http_bad_request(f'Could not read file: {exc}')",
    "    try:",
    "        paper = await parse_uploaded_pdf(pdf_bytes=pdf_bytes, filename=file.filename or 'upload.pdf')",
    "    except PaperTooLargeError as exc:",
    "        raise http_payload_too_large(str(exc))",
    "    except PaperParseError as exc:",
    "        raise http_unprocessable(str(exc))",
    "    return ParseResponse(",
    "        arxiv_id=paper.arxiv_id, title=paper.title, authors=paper.authors,",
    "        abstract=paper.abstract, page_count=paper.page_count,",
    "        word_count=paper.word_count, source=PaperSource.PDF_UPLOAD,",
    "    )",
]))

# ── app/api/routes/analyze.py ─────────────────────────────────────────────────
w("app/api/routes/analyze.py", "\n".join([
    "from fastapi import APIRouter, UploadFile, File",
    "from app.models.paper import ParseArxivRequest, AnalyzeResponse",
    "from app.services.parser import fetch_arxiv_paper, parse_uploaded_pdf",
    "from app.services.analyzer import get_analyzer",
    "from app.core.exceptions import (",
    "    PaperFetchError, PaperParseError, PaperTooLargeError, InvalidArxivIdError,",
    "    AnalysisError, ClaudeAPIError,",
    "    http_bad_request, http_not_found, http_payload_too_large,",
    "    http_service_unavailable, http_unprocessable,",
    ")",
    "from app.core.logging import get_logger",
    "",
    'router = APIRouter(prefix="/analyze", tags=["analyze"])',
    "logger = get_logger(__name__)",
    "",
    "",
    '@router.post("/arxiv", response_model=AnalyzeResponse)',
    "async def analyze_arxiv(request: ParseArxivRequest) -> AnalyzeResponse:",
    "    try:",
    "        paper = await fetch_arxiv_paper(request.url)",
    "    except InvalidArxivIdError as exc:",
    "        raise http_bad_request(str(exc))",
    "    except PaperFetchError as exc:",
    "        raise http_not_found(str(exc))",
    "    except PaperTooLargeError as exc:",
    "        raise http_payload_too_large(str(exc))",
    "    except PaperParseError as exc:",
    "        raise http_unprocessable(str(exc))",
    "    try:",
    "        analyzer = get_analyzer()",
    "        analysis, tokens_used = await analyzer.analyze(paper)",
    "    except ClaudeAPIError as exc:",
    "        raise http_service_unavailable(str(exc))",
    "    except AnalysisError as exc:",
    "        raise http_unprocessable(str(exc))",
    "    except Exception as exc:",
    '        logger.exception("Unexpected error: %s", exc)',
    '        raise http_service_unavailable("An unexpected error occurred.")',
    "    return AnalyzeResponse(arxiv_id=paper.arxiv_id, analysis=analysis, tokens_used=tokens_used)",
    "",
    "",
    '@router.post("/upload", response_model=AnalyzeResponse)',
    "async def analyze_upload(file: UploadFile = File(...)) -> AnalyzeResponse:",
    "    content_type = file.content_type or ''",
    "    if 'pdf' not in content_type and not (file.filename or '').lower().endswith('.pdf'):",
    "        raise http_bad_request(f'Only PDF files accepted. Got: {content_type!r}')",
    "    try:",
    "        pdf_bytes = await file.read()",
    "    except Exception as exc:",
    "        raise http_bad_request(f'Could not read file: {exc}')",
    "    try:",
    "        paper = await parse_uploaded_pdf(pdf_bytes=pdf_bytes, filename=file.filename or 'upload.pdf')",
    "    except PaperTooLargeError as exc:",
    "        raise http_payload_too_large(str(exc))",
    "    except PaperParseError as exc:",
    "        raise http_unprocessable(str(exc))",
    "    try:",
    "        analyzer = get_analyzer()",
    "        analysis, tokens_used = await analyzer.analyze(paper)",
    "    except ClaudeAPIError as exc:",
    "        raise http_service_unavailable(str(exc))",
    "    except AnalysisError as exc:",
    "        raise http_unprocessable(str(exc))",
    "    return AnalyzeResponse(arxiv_id=paper.arxiv_id, analysis=analysis, tokens_used=tokens_used)",
]))

# ── tests/conftest.py ─────────────────────────────────────────────────────────
w("tests/conftest.py", "\n".join([
    "import os",
    'os.environ.setdefault("ANTHROPIC_API_KEY", "sk-ant-test-key-for-testing")',
    'os.environ.setdefault("SUPABASE_URL", "https://test.supabase.co")',
    'os.environ.setdefault("SUPABASE_SERVICE_KEY", "test-service-key")',
    'os.environ.setdefault("ENVIRONMENT", "test")',
    'os.environ.setdefault("CORS_ORIGINS", \'["http://localhost:3000"]\')',
]))

# ── pytest.ini ────────────────────────────────────────────────────────────────
w("pytest.ini", "\n".join([
    "[pytest]",
    "asyncio_mode = auto",
    "testpaths = tests",
    "python_files = test_*.py",
    "python_classes = Test*",
    "python_functions = test_*",
]))

print("\nDone. Run: python -m pytest tests/ -v")