"""
PaperForge data models — structured results returned by the SDK.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional
from pathlib import Path


@dataclass
class PaperAnalysis:
    """
    Structured methodology extraction from a research paper.

    Attributes:
        title: Exact paper title
        problem_statement: 1-2 sentence description of the problem
        proposed_method: 3-5 sentence description of the approach
        key_algorithm: Name of the core algorithm (e.g. "Transformer", "XGBoost")
        novelty: What is specifically new vs prior work
        datasets_used: List of datasets mentioned in the paper
        evaluation_metrics: List of metrics used for evaluation
        reported_results: Dict of metric -> value from the paper
        implementation_difficulty: "easy", "medium", or "hard"
        dependencies: Python packages needed to implement this
        reproducibility_notes: Gaps or warnings for reproduction
        paper_type: "empirical", "theoretical", "survey", etc.
        is_implementable: Whether core method can be coded
        arxiv_id: arXiv ID if available
        tokens_used: Claude API tokens consumed
    """
    title: str
    problem_statement: str
    proposed_method: str
    key_algorithm: str
    novelty: str
    datasets_used: list[str]
    evaluation_metrics: list[str]
    reported_results: dict[str, str]
    implementation_difficulty: str
    dependencies: list[str]
    reproducibility_notes: str
    paper_type: str
    is_implementable: bool
    arxiv_id: Optional[str] = None
    tokens_used: int = 0

    @property
    def is_hard(self) -> bool:
        return self.implementation_difficulty == "hard"

    @property
    def is_easy(self) -> bool:
        return self.implementation_difficulty == "easy"

    def __repr__(self) -> str:
        return (
            f"PaperAnalysis(title={self.title!r}, "
            f"algorithm={self.key_algorithm!r}, "
            f"difficulty={self.implementation_difficulty!r})"
        )


@dataclass
class GeneratedCode:
    """
    AI-generated Python implementation of a paper's algorithm.

    Attributes:
        strategy: "full", "core", or "skeleton"
        code: Complete Python source code
        explanation: What the code implements
        usage_example: Minimal example showing how to use it
        install_command: pip install command for dependencies
        limitations: What is NOT implemented vs the full paper
        estimated_lines: Line count of generated code
        arxiv_id: arXiv ID if available
        tokens_used: Claude API tokens consumed
    """
    strategy: str
    code: str
    explanation: str
    usage_example: str
    install_command: str
    limitations: str
    estimated_lines: int
    arxiv_id: Optional[str] = None
    tokens_used: int = 0

    def save(self, path: str | Path) -> Path:
        """
        Save the generated code to a .py file.

        Args:
            path: File path or directory. If directory, saves as
                  ``paperforge_implementation.py`` inside it.

        Returns:
            Path to the saved file.

        Example::

            code = pf.generate("https://arxiv.org/abs/1706.03762")
            saved = code.save("transformer_attention.py")
            print(f"Saved to {saved}")
        """
        p = Path(path)
        if p.is_dir() or not p.suffix:
            p.mkdir(parents=True, exist_ok=True)
            p = p / "paperforge_implementation.py"
        else:
            p.parent.mkdir(parents=True, exist_ok=True)

        header = f'"""\nGenerated by PaperForge SDK\nAlgorithm: {self.arxiv_id or "unknown"}\nStrategy: {self.strategy}\n"""\n\n'
        p.write_text(header + self.code, encoding="utf-8")
        return p

    def print_usage(self) -> None:
        """Print the usage example to stdout."""
        print(f"\n{'─' * 60}")
        print("USAGE EXAMPLE")
        print('─' * 60)
        print(self.usage_example)
        print('─' * 60)

    def __repr__(self) -> str:
        return (
            f"GeneratedCode(strategy={self.strategy!r}, "
            f"lines={self.estimated_lines}, "
            f"arxiv_id={self.arxiv_id!r})"
        )


@dataclass
class MetricResult:
    """A single benchmark metric comparing your results to paper results."""
    name: str
    your_value: Optional[float]
    paper_value: Optional[str]
    unit: str = ""
    higher_is_better: bool = True
    gap_pct: Optional[float] = None

    @property
    def beat_paper(self) -> Optional[bool]:
        """True if your result beats the paper, False if worse, None if unknown."""
        if self.gap_pct is None:
            return None
        if self.higher_is_better:
            return self.gap_pct >= 0
        return self.gap_pct <= 0

    def __repr__(self) -> str:
        gap = f" ({self.gap_pct:+.1f}%)" if self.gap_pct is not None else ""
        return f"MetricResult({self.name}={self.your_value}{gap})"


@dataclass
class BenchmarkResult:
    """
    Results from benchmarking generated code against your dataset.

    Attributes:
        status: "success", "partial", "error", or "timeout"
        dataset_name: Name of the uploaded CSV file
        dataset_rows: Number of rows in your dataset
        dataset_cols: Number of columns in your dataset
        metrics: List of MetricResult objects
        interpretation: Claude's plain-English analysis
        stdout: Raw output from code execution
        execution_time_ms: Time taken in milliseconds
        error_message: Error details if status is "error"
        tokens_used: Claude API tokens consumed
    """
    status: str
    dataset_name: str
    dataset_rows: int
    dataset_cols: int
    metrics: list[MetricResult] = field(default_factory=list)
    interpretation: str = ""
    stdout: str = ""
    execution_time_ms: int = 0
    error_message: Optional[str] = None
    tokens_used: int = 0

    @property
    def succeeded(self) -> bool:
        return self.status in ("success", "partial")

    def __repr__(self) -> str:
        return (
            f"BenchmarkResult(status={self.status!r}, "
            f"metrics={len(self.metrics)}, "
            f"dataset={self.dataset_rows}rows)"
        )


@dataclass
class PaperResult:
    """
    Complete result from the full PaperForge pipeline.
    Combines analysis + generated code in one object.

    Example::

        result = pf.paper("https://arxiv.org/abs/1706.03762")
        print(result.analysis.key_algorithm)
        result.code.save("output/")
        print(f"Total tokens: {result.total_tokens}")
    """
    arxiv_id: Optional[str]
    analysis: PaperAnalysis
    code: GeneratedCode
    total_tokens: int

    def save_code(self, path: str | Path = ".") -> Path:
        """Convenience wrapper — save generated code to path."""
        return self.code.save(path)

    def __repr__(self) -> str:
        return (
            f"PaperResult(arxiv_id={self.arxiv_id!r}, "
            f"algorithm={self.analysis.key_algorithm!r}, "
            f"tokens={self.total_tokens})"
        )
